from __future__ import annotations

from typing import Any, Iterator, Protocol

from aether_runner.models.schemas import CanonicalRequest, CapabilityManifest


class ModelAdapter(Protocol):
    def capabilities(self) -> CapabilityManifest: ...

    def normalize_request(self, req: CanonicalRequest) -> CanonicalRequest: ...

    def build_inputs(self, req: CanonicalRequest, assets: list[dict[str, Any]]) -> dict[str, Any]: ...

    def generate(self, prepared: dict[str, Any]) -> dict[str, Any]: ...

    def stream_generate(self, prepared: dict[str, Any]) -> Iterator[dict[str, Any]]: ...

    def parse_output(self, raw: dict[str, Any]) -> dict[str, Any]: ...

    def parse_tools(self, raw: dict[str, Any]) -> list[dict[str, Any]]: ...
